name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install Dependencies
        run: npm install --no-warnings

      - name: Get version and name from package.json
        id: get_version_name
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
          echo "::set-output name=name::$(node -p "require('./package.json').name")"

      - name: Create or Get Release ID
        id: create_or_get_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag: "v${{ steps.get_version_name.outputs.version }}"

      - name: Build Electron App
        run: npm run dist -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
