name: Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.15.0'

            - name: Install Dependencies
              run: npm install

            - name: Get version and name from package.json
              id: get_version_name
              run: |
                  echo "::set-output name=version::$(node -p "require('./package.json').version")"
                  echo "::set-output name=name::$(node -p "require('./package.json').name")"

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: v${{ steps.get_version_name.outputs.version }}
                  release_name: Release ${{ steps.get_version_name.outputs.version }}
                  draft: true
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Electron App
              run: npm run dist
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
